spring:
  cloud:
    discovery:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
    hostname: localhost
    ipAddr: 127.0.0.1